In [1]:
import pandas as pd
import duckdb
from pathlib import Path
import openpyxl
print("openpyxl is working") # for reading excel files

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

openpyxl is working

In [2]:
df = pd.read_csv("../data/processed/netflix.csv")

# Register in DuckDB
duckdb.register("netflix",df)
df.shape

(458338, 15)

In [3]:
df.head()

,Unnamed: 0,country_name,country_iso2,week,country_category,country_weekly_rank,show_title,season_title,country_cumulative_weeks_in_top_10,global_category,global_weekly_rank,global_weekly_hours_viewed,runtime,global_weekly_views,global_cumulative_weeks_in_top_10
0,0,Argentina,AR,2026-03-15,Films,1,War Machine,NaN,2,Films (English),1.0,80600000.0,109.002,44400000.0,2.0
1,1,Argentina,AR,2026-03-15,Films,2,Strangers in the Park,NaN,2,Films (Non-English),10.0,1600000.0,115.998,800000.0,2.0
2,2,Argentina,AR,2026-03-15,Films,3,Joker: Folie à Deux,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Argentina,AR,2026-03-15,Films,4,Trolls Band Together,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Argentina,AR,2026-03-15,Films,5,Double Jeopardy,NaN,1,Films (English),5.0,6200000.0,106.002,3500000.0,1.0

In [4]:
duckdb.sql("""
DESCRIBE netflix
""").df()

                           column_name column_type null   key default extra
0                           Unnamed: 0      BIGINT  YES  None    None  None
1                         country_name     VARCHAR  YES  None    None  None
2                         country_iso2     VARCHAR  YES  None    None  None
3                                 week     VARCHAR  YES  None    None  None
4                     country_category     VARCHAR  YES  None    None  None
5                  country_weekly_rank      BIGINT  YES  None    None  None
6                           show_title     VARCHAR  YES  None    None  None
7                         season_title     VARCHAR  YES  None    None  None
8   country_cumulative_weeks_in_top_10      BIGINT  YES  None    None  None
9                      global_category     VARCHAR  YES  None    None  None
10                  global_weekly_rank      DOUBLE  YES  None    None  None
11          global_weekly_hours_viewed      DOUBLE  YES  None    None  None
12                             runtime      DOUBLE  YES  None    None  None
13                 global_weekly_views      DOUBLE  YES  None    None  None
14   global_cumulative_weeks_in_top_10      DOUBLE  YES  None    None  None

## Dataset Checks
Validate structure first before analysis

In [5]:
duckdb.sql("""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT show_title) AS unique_show_titles,
    COUNT(DISTINCT week) AS unique_weeks,
    COUNT(DISTINCT country_name) AS unique_countries         
FROM netflix
""").df()

   total_rows  unique_show_titles  unique_weeks  unique_countries
0      458338               11060           246                94